name: Gradle

on:
  push:

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@8edcb1bdb4e267140fa742c62e395cd74f332709 # updated on 2025-07-23
    
    - uses: actions/setup-java@e9343db97e09d87a3c50e544105d99fe912c204b # updated on 2025-07-30
      with:
        distribution: 'temurin'
        java-version: 17
        
    - uses: gradle/actions/setup-gradle@017a9effdb900e5b5b2fddfb590a105619dca3c3 # v4.4.2
      with:
        gradle-version: wrapper
        
    - name: Build app
      run: gradle assembleRelease -Pinclude-analytics -Penable-updater
