name: Gradle

on:
  push:

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2 # updated on Jan 16
    
    - uses: actions/setup-java@f4f1212c880fdec8162ea9a6493f4495191887b4 # updated on Apr 16
      with:
        distribution: 'temurin'
        java-version: 17
        
    - uses: gradle/actions/setup-gradle@8379f6a1328ee0e06e2bb424dadb7b159856a326 # v4.4.0
      with:
        gradle-version: 8.13
        
    - name: Build app
      run: gradle assembleRelease -Pinclude-analytics -Penable-updater
