name: Gradle

on:
  push:

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4.2.2
    
    - uses: actions/setup-java@v4.7.0
      with:
        distribution: 'temurin'
        java-version: 17
        
    - uses: gradle/actions/setup-gradle@v4.3.0
      with:
        gradle-version: 8.13
        
    - name: Build app
      run: gradle assembleRelease -Pinclude-analytics -Penable-updater
